version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  __main__:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
